### ISSUE TITLE
nightwatch hangs when directory is removed with --dir

### ISSUE THREAD

**Issue by matti** [jakolehm/nightwatch#9]
```
while true do;
  find . | nightwatch --debug --dir --exit-on-change=255 ping google.com
  echo "restart"
done
```

1. touch any file --> exits
2. mkdir "dir" --> nothing happens
3. touch "dir/file" --> exits
4. rm file --> nothing happens
5. rmdir dir --> nothing happens
6. touch any file --> nothing happens (hangs)

**Comment by jakolehm** [comment]
Fixed.
